### ISSUE TITLE
latest version (v1.3.0) not available in maven registry

### ISSUE THREAD

**Issue by raniero-sequence** [trycourier/courier-java#15]
## Expected Behavior
Expected latest version of courier-java in maven registry to be the latest released/tagged version in github.com/trycourier/courier-java

## Actual Behavior
The latest version available in maven registry is v1.2.0 (https://search.maven.org/search?q=a:courier-java)

**Comment by tk26** [comment]
thanks for bringing this up to our attention @raniero-sequence - we've pushed 1.3.0 up.

**Comment by raniero-sequence** [comment]
great! when i checked again it was there so i closed the ticket proactively. thanks for taking care of it.

**Comment by tk26** [comment]
No worries at all - would love to hear any feedback you may have on the SDK @raniero-sequence
