### ISSUE TITLE
Version 1.5.0 not available in search.maven.org

### ISSUE THREAD

**Issue by ridhwaans** [trycourier/courier-java#21]
## Expected Behavior
Would like the [v1.5](https://github.com/trycourier/courier-java/releases/tag/v1.5.0) release to be available in Sonatype | Maven Central Repository Search

## Actual Behavior
As of date, v1.4 is the last one available in https://search.maven.org/artifact/com.courier/courier-java

**Comment by crrojas88** [comment]
Hi there. We will release this on Monday. Thank you!

**Comment by tk26** [comment]
@ridhwaans @crrojas88 quick f/up on this - we've released [v1.5.0](https://repo1.maven.org/maven2/com/courier/courier-java/1.5.0/) - it could take a bit until major public distributors index this but it's out there :)
