### ISSUE TITLE
User profile create and update results in InvalidDefinitionException: Cannot construct instance of `com.courier.api.resources.profiles.types.MergeProfileResponse`

### ISSUE THREAD

**Issue by JohnneyChen-mio** [trycourier/courier-java#56]
When creating or replacing a user profile using `courier().profiles().create()` and `courier().profiles().replace()`, it results in the error `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.courier.api.resources.profiles.types.MergeProfileResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator) at [Source: (String)"{"status":"SUCCESS"}"; line: 1, column: 2]` The request itself is successful as the data is updated on courier but the function call always throws the exception due to lack of constructor for MergeProfileResponse and ReplaceProfileResponse. Currently using courier-java-3.0.3.jar

**Comment by dsinghvi** [comment]
Hey @JohnneyChen-mio thanks for filing this issue, the Courier Java SDK will be regenerated today with a fix.

**Comment by JohnneyChen-mio** [comment]
@dsinghvi Hello, I was just wondering if the regenerated SDK is available yet?

**Comment by dsinghvi** [comment]
@JohnneyChen-mio sorry for the delay, the source code has been pushed but not published to maven just yet.

**Comment by dsinghvi** [comment]
@JohnneyChen-mio you should be set with version `3.1.2`. Please holler if you need anything and you can email me at `deep@buildwithfern.com`
