### ISSUE TITLE
[Question ]Override Channels

### ISSUE THREAD

**Issue by madelacerda** [trycourier/courier-java#59]
Hello, I have a question rather than a bug report. I’ve been trying for several days to find a way to override certain fields in the message I’m sending via the Courier SDK, based on certain criteria. For instance, if my client meets certain criteria, I want to change the from field of the message. However, I haven’t been able to find a way to override the channel of the TemplateMessage. Could anyone assist me with this?

**Comment by bwebs** [comment]
[Overrides](https://www.courier.com/docs/platform/sending/#overrides-advanced) is how you would do this with ContentMessage or TemplateMessage. However, if you are using TemplateMessage, the easier route might be to do this in the template in Courier Studio.
On the Email Channel Settings, you can
1. Set the default from which would override the provider default from
2. Check your Overrides in the same settings. It grabs from there, but this accepts Jsonnet. You could do something like this 
```
{
  bcc: template("bcc"),
  cc: template("cc"),
  from: template("from"),
  html: template("html"),
  replyTo: template("replyTo"),
  subject: template("subject"),
  text: template("text")
} + {
  [if std.isString(data("from")) then 'from']: data("from")
}
```
![image](https://github.com/user-attachments/assets/2890d641-1d0f-4238-958b-f61f2e97d293)

Your data object only contains a `from` key when you want to override it.
Feel free to re-open if you have more questions!
